--Nome: Caike Dametto RM: 558614
--Nome: Guilhetme Janunzzi RM: 558461

CREATE TABLE T_MM_FILIAL (
    CD_FILIAL         NUMBER(8) NOT NULL,
    NM_FILIAL         VARCHAR2(150) NOT NULL,
    DS_ENDERECO       VARCHAR2(255) NOT NULL,
    NM_CIDADE         VARCHAR2(100) NOT NULL,
    SG_ESTADO         VARCHAR2(2) NOT NULL,
    NR_LINHA          NUMBER(4) NOT NULL,
    NR_COLUNA         NUMBER(4) NOT NULL,
    QT_CAPACIDADE_MAX NUMBER(6) NOT NULL
);

ALTER TABLE T_MM_FILIAL ADD CONSTRAINT PK_FILIAL_MOTOMAP PRIMARY KEY ( cd_filial );

CREATE TABLE T_MM_USUARIO (
    CD_USUARIO           NUMBER(9) NOT NULL,
    CD_FILIAL             NUMBER(8) NOT NULL,
    NM_USUARIO            VARCHAR2(150) NOT NULL,
    DS_EMAIL              VARCHAR2(100) NOT NULL,
    DS_SENHA              VARCHAR2(200) NOT NULL,
    DS_CARGO               VARCHAR2(20) NOT NULL
);

ALTER TABLE T_MM_USUARIO ADD CONSTRAINT PK_USUARIO_MOTOMAP PRIMARY KEY ( cd_usuario );
ALTER TABLE T_MM_USUARIO ADD CONSTRAINT FK_CD_FILIAL_USUARIO FOREIGN KEY ( cd_filial ) REFERENCES T_MM_FILIAL ( cd_filial );

CREATE TABLE T_MM_POSICAO_PATIO (
    CD_POSICAO            NUMBER(6) NOT NULL,
    CD_FILIAL             NUMBER(8) NOT NULL,
    CD_IDENTIFICACAO      VARCHAR2(10) NOT NULL,
    NR_LINHA               NUMBER(4) NOT NULL,
    NR_COLUNA             NUMBER(4) NOT NULL,
    DS_AREA               VARCHAR2(50) NOT NULL,
    DS_OCUPADO             NUMBER(1) NOT NULL CHECK (ds_ocupado IN (0,1)) 
);

ALTER TABLE T_MM_POSICAO_PATIO ADD CONSTRAINT PK_POSICAO_MOTOMAP PRIMARY KEY ( cd_posicao );
ALTER TABLE T_MM_POSICAO_PATIO ADD CONSTRAINT FK_CD_FILIAL_POSICAO FOREIGN KEY ( cd_filial ) REFERENCES T_MM_FILIAL ( cd_filial );

CREATE TABLE T_MM_MOTO (
    CD_MOTO               NUMBER(9) NOT NULL,
    CD_FILIAL             NUMBER(8) NOT NULL,
    DS_PLACA              VARCHAR2(8),
    DS_CHASSI             VARCHAR2(17),  
    NM_MODELO             VARCHAR2(50) NOT NULL,
    NR_ANO                NUMBER(4) NOT NULL,
    DS_STATUS             VARCHAR2(20) NOT NULL
);

ALTER TABLE T_MM_MOTO ADD CONSTRAINT PK_MOTO_MOTOMAP PRIMARY KEY ( cd_moto );
ALTER TABLE T_MM_MOTO ADD CONSTRAINT FK_CD_FILIAL_MOTO FOREIGN KEY ( cd_filial ) REFERENCES T_MM_FILIAL ( cd_filial );

CREATE TABLE T_MM_PROBLEMA (
    CD_PROBLEMA             NUMBER(9) NOT NULL,
    CD_MOTO                 NUMBER(9) NOT NULL,
    CD_USUARIO              NUMBER(9) NOT NULL,
    DS_TIPO                 VARCHAR2(20) NOT NULL,
    DS_DESCRICAO            VARCHAR2(255) NOT NULL,
    DT_REGISTRO             DATE NOT NULL,
    DS_RESOLVIDO            NUMBER(1) NOT NULL CHECK (ds_resolvido IN (0,1))
);

ALTER TABLE T_MM_PROBLEMA ADD CONSTRAINT PK_PROBLEMA_MOTOMAP PRIMARY KEY ( cd_problema );
ALTER TABLE T_MM_PROBLEMA ADD CONSTRAINT FK_MOTO_PROBLEMA FOREIGN KEY ( cd_moto ) REFERENCES T_MM_MOTO ( cd_moto );
ALTER TABLE T_MM_PROBLEMA ADD CONSTRAINT FK_USUARIO_PROBLEMA FOREIGN KEY ( cd_usuario ) REFERENCES T_MM_USUARIO ( cd_usuario );

CREATE TABLE T_MM_HISTORICO_POSICAO (
    CD_HISTORICO                  NUMBER(10) NOT NULL,
    CD_MOTO                       NUMBER(9) NOT NULL,
    CD_POSICAO                    NUMBER(6) NOT NULL,
    DT_INICIO                     DATE NOT NULL,
    DT_FIM                        DATE
);

ALTER TABLE T_MM_HISTORICO_POSICAO ADD CONSTRAINT PK_HISTORICO_MOTOMAP PRIMARY KEY ( cd_historico );
ALTER TABLE T_MM_HISTORICO_POSICAO ADD CONSTRAINT FK_MOTO_HISTORICO FOREIGN KEY ( cd_moto ) REFERENCES T_MM_MOTO ( cd_moto );
ALTER TABLE T_MM_HISTORICO_POSICAO ADD CONSTRAINT FK_POSICAO_HISTORICO FOREIGN KEY ( cd_posicao ) REFERENCES T_MM_POSICAO_PATIO ( cd_posicao );

CREATE TABLE T_MM_MOVIMENTACAO (
    CD_MOVIMENTACAO         NUMBER(10) NOT NULL,
    CD_USUARIO              NUMBER(9) NOT NULL,
    CD_MOTO                 NUMBER(9) NOT NULL,
    DS_TIPO                 VARCHAR2(20) NOT NULL,
    DT_HORA                 DATE NOT NULL,
    DS_OBSERVACOES          VARCHAR2(255) NOT NULL
);

ALTER TABLE T_MM_MOVIMENTACAO ADD CONSTRAINT PK_MOVIMENTACAO_MOTOMAP PRIMARY KEY ( cd_movimentacao );
ALTER TABLE T_MM_MOVIMENTACAO ADD CONSTRAINT FK_USUARIO_MOVIMENTACAO FOREIGN KEY ( cd_usuario ) REFERENCES T_MM_USUARIO ( cd_usuario );
ALTER TABLE T_MM_MOVIMENTACAO ADD CONSTRAINT FK_MOTO_MOVIMENTACAO FOREIGN KEY ( cd_moto ) REFERENCES T_MM_MOTO ( cd_moto );