--Nome: Caike Dametto RM: 558614
--Nome: Guilhetme Janunzzi RM: 558461

DROP TABLE T_MM_FILIAL CASCADE CONSTRAINTS;

DROP TABLE T_MM_USUARIO CASCADE CONSTRAINTS;

DROP TABLE T_MM_POSICAO_PATIO CASCADE CONSTRAINTS;

DROP TABLE T_MM_MOTO CASCADE CONSTRAINTS;

DROP TABLE T_MM_PROBLEMA CASCADE CONSTRAINTS;

DROP TABLE T_MM_HISTORICO_POSICAO CASCADE CONSTRAINTS;

DROP TABLE T_MM_MOVIMENTACAO CASCADE CONSTRAINTS;